version: '1'
services:
  backend:
    image: backend:1.0
    ports:
      - "8080:8080"

  backend-frontend:
    image: backend-frontend:1.0
    ports:
      - "8081:8081"

  api-gateway:
    image: api-gateway:1.0
    ports:
      - "8082:8082"

  eureka:
    image: eureka:1.0
    ports:
      - "8761:8761"